/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:664297ac-c8f1-45be-8a52-6583c5609606",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TSimgfdR5",
    "aws_user_pools_web_client_id": "78c53cv78vuo38sbdjp9coabgu",
    "oauth": {
        "domain": "gp6safedalbox.auth.us-east-1.amazoncognito.com"
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        },
        {
            "name": "BookTrip_dev",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
